# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: "github-actions"
    cooldown:
      default-days: 7
    directory: "/"
    groups:
      gha-deps:
        patterns:
          - "*"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    cooldown:
      default-days: 7
    directory: "/"
    groups:
      npm-deps:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
