import versions from "./versions.json";

const sidebars = {
  docsSidebar: [
    { type: "autogenerated", dirName: "docs" },
    {
      type: "html",
      value: "<hr/>",
      className: "margin-vert--none",
    },
    {
      type: "ref",
      id: "reference/global-options",
      label: "Reference",
    },
  ],
  referenceSidebar: [
    { type: "autogenerated", dirName: "reference" },
    {
      type: "html",
      value: "<hr/>",
      className: "margin-vert--none",
    },
    {
      type: "ref",
      id: "docs/introduction/how-does-pants-work",
      label: "Docs",
    },
  ],
  releaseNotesSidebar: [
    {
      type: "category",
      label: "Release Notes",
      link: {
        type: "doc",
        id: "notes/" + versions[0] + ".x",
      },
      items: versions
        .map((v) => ({ type: "doc", id: "notes/" + v + ".x" })),
    },
  ],
};

module.exports = sidebars;
